name: kami
description: A package for parsing coded DioErrors into hierarchical Exception trees.
version: 0.0.1
repository: https://github.com/ErrApparent/kami

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
   dio: ^4.0.4
   meta: ^1.7.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
